Repository kubevirt/managed-tenant-quota, pull requests merged in 2023-10, with the labels that each got.

#29 Fix kubevirt apply command
  cluster-up/up.sh
  hack/update-kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, size/XS, lgtm

#30 Fix kubevirt apply command
  cluster-up/up.sh
  hack/update-kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, size/XS, lgtm

#28 Enqueue all blocking migrations periodically and Update validatingWebhookConfiguration when it's invalid
  pkg/mtq-controller/vmmrq-controller/vmmrq-controller.go
  pkg/validating-webhook-lock/validating-webhook-lock.go
  tests/mtq_operator_test.go
Labels: dco-signoff: yes, release-note-none, size/L, lgtm, approved

#36 Fix vmmrq creation with no pending migrations
  pkg/mtq-controller/vmmrq-controller/vmmrq-controller.go
Labels: dco-signoff: yes, release-note-none, size/XS, lgtm, approved
