Repository kubevirt/managed-tenant-quota, pull requests merged in 2023-09, with the labels that each got.

#14 reduce rbac privileges
  _out/manifests/release/mtq-operator.yaml
  _out/manifests/templates/release/mtq-operator.yaml.j2
  manifests/generated/operator-everything.yaml.in
  manifests/generated/operator-everything.yaml.in.j2
  pkg/mtq-operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/L

#19 Add RBAC for configmaps finalizers for mtq-operator
  pkg/mtq-operator/resources/operator/operator.go
Labels: dco-signoff: yes, size/S, release-note, lgtm, approved

#22 Protect the MTQ status
  pkg/mtq-operator/controller.go
  pkg/mtq-operator/resources/crds_generated.go
  pkg/mtq-operator/resources/operator/operator.go
  staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#23 [Release-v1.1]Backport
  pkg/mtq-operator/controller.go
  pkg/mtq-operator/resources/crds_generated.go
  pkg/mtq-operator/resources/operator/operator.go
  staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
Labels: dco-signoff: yes, release-note-none, size/M, lgtm

#24 Add get namespaces permission to rbac
  manifests/examples/VirtualMachineMigrationResourceQuotaExample.yaml
  manifests/examples/migration-job.yaml
  manifests/examples/rq.yaml
  manifests/examples/vmi-migratable.yaml
  pkg/mtq-operator/resources/cluster/controller.go
Labels: dco-signoff: yes, release-note-none, size/M
